services:
  microservice-template:
    build: 
          context: .
          dockerfile: ./microservice-template/Dockerfile
    ports:
      - "${MICROSERVICE_TEMPLATE_PORT}:${MICROSERVICE_TEMPLATE_PORT}"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${STOCK_ORDER_DATABASE_URL}
      PORT: ${MICROSERVICE_TEMPLATE_PORT}
    networks:
       - go-network
    depends_on:
      stock-order-db:
        condition: service_healthy
  matching-engine-service:
    build: 
          context: .
          dockerfile: ./matching-engine-service/Dockerfile
    ports:
      - "${MATCHING_ENGINE_PORT}:${MATCHING_ENGINE_PORT}"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${STOCK_ORDER_DATABASE_URL}
      DATABASE_URL_TRANSACTION: ${STOCK_TRANSACTION_DATABASE_URL}
      PORT: ${MATCHING_ENGINE_PORT}
    depends_on:
      stock-order-db:
        condition: service_healthy
    networks:
       - go-network

  order-executor-service:
    build:
          context: .
          dockerfile: ./order-executor-service/Dockerfile
    ports:
      - "${ORDER_EXECUTOR_PORT}:${ORDER_EXECUTOR_PORT}"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${STOCK_ORDER_DATABASE_URL}
      DATABASE_URL_TRANSACTION: ${STOCK_TRANSACTION_DATABASE_URL}
      PORT: ${ORDER_EXECUTOR_PORT}
    depends_on:
      stock-order-db:
        condition: service_healthy
    networks:
       - go-network

  stock-order-db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${STOCK_ORDER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${STOCK_ORDER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${STOCK_ORDER_POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./stock-order-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $STOCK_ORDER_POSTGRES_USER -d $STOCK_ORDER_POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - go-network

  stock-transaction-db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${STOCK_TRANSACTION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${STOCK_TRANSACTION_POSTGRES_PASSWORD}
      POSTGRES_DB: ${STOCK_TRANSACTION_POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./stock-transaction-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $STOCK_TRANSACTION_POSTGRES_USER -d $STOCK_TRANSACTION_POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - go-network

  stock-db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${STOCK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${STOCK_POSTGRES_PASSWORD}
      POSTGRES_DB: ${STOCK_POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./stock-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $STOCK_POSTGRES_USER -d $STOCK_POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - go-network


volumes:
  db-data:

networks:
  go-network:
    driver: bridge           # Use a bridge network to enable container communication