services:
  microservice-template:
    build: 
          context: .
          dockerfile: ./microservice-template/Dockerfile
    ports:
      - "8000:8000"
    networks:
       - go-network

  matching-engine-microservice:
    build: 
          context: .
          dockerfile: ./matching-engine-service/Dockerfile
    ports:
      - "8080:8080"
    networks:
       - go-network

networks:
  go-network:
    driver: bridge           # Use a bridge network to enable container communication