version: "3.8"

services:
  server:
    build: 
      context: .
      dockerfile: ./server/Dockerfile  
    ports:
      - "8000:8000"
    networks:
      - go-network

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
