services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    env_file:
      - .env # 👈 Loads env vars from the root .env file
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env # 👈 PostgreSQL also reads from the same .env file
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
