# Allow replication connections from any IP address
host    replication     trans_repl_user     0.0.0.0/0       trust
host    all             all                 0.0.0.0/0       md5
local   all             all                                 trust
