# TYPE  DATABASE        USER            ADDRESS                 METHOD
# Allow Unix socket connections for the main application user (e.g., for healthchecks)
local   all             transaction          trust  # Or trust if you absolutely must for now

# Allow replication connections using the replication user
host    replication     trans_repl_user     0.0.0.0/0       trust # Or md5

# Allow TCP/IP connections for all users/databases from any IP (using password)
host    all             all                 0.0.0.0/0       md5
