CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE stocks (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    Date_Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Date_Modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Name TEXT NOT NULL
);