CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE stocks (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DateModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Name TEXT NOT NULL
);