CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE stockOrder (
    ID UUID PRIMARY KEY,
    StockID SERIAL,
    ParentStockOrderID SERIAL,
    DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DateModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IsBuy BOOLEAN NOT NULL,
    OrderType TEXT NOT NULL,
    Price DECIMAL NOT NULL,
    Quantity INT NOT NULL,
    UserID SERIAL NOT NULL,
    FOREIGN KEY (ParentStockOrderID) REFERENCES stockOrder(ID)
);