CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE Users (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    Username VARCHAR(50) NOT NULL,
    Password TEXT NOT NULL,
    Name TEXT NOT NULL,
    Date_Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Date_Modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

