CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE Wallets (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    User_ID UUID NOT NULL,
    Balance DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
    DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DateModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UserStocks (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    User_ID UUID NOT NULL,
    StockID UUID NOT NULL,
    StockName TEXT NOT NULL,
    Quantity INT NOT NULL,
    DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DateModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);