CREATE TABLE Wallets (
    ID SERIAL PRIMARY KEY,
    UserID SERIAL NOT NULL,
    Balance DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
    DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DateModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UserStocks (
    ID SERIAL PRIMARY KEY,
    UserID SERIAL NOT NULL,
    StockID SERIAL NOT NULL,
    StockName TEXT NOT NULL,
    Quantity INT NOT NULL,
    DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DateModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
