-- SET log_min_messages = NOTICE;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
DROP TABLE IF EXISTS wallet_transactions CASCADE;
DROP TABLE IF EXISTS stock_transactions CASCADE;
DROP TABLE IF EXISTS userstocks CASCADE;
DROP TABLE IF EXISTS wallets CASCADE;

CREATE TABLE wallets (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL,
    balance DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE wallets
    ADD CONSTRAINT balance_nonnegative CHECK (balance >= 0);

CREATE TABLE user_stocks (
    id UUID DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL,
    stock_id UUID NOT NULL,
    stock_name TEXT NOT NULL,
    quantity INT NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, stock_id)
);

CREATE TABLE stock_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    stock_id UUID,
    parent_stock_transaction_id UUID,
    user_stock_transaction_id UUID,
    wallet_transaction_id UUID,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    order_status TEXT NOT NULL,
    is_buy BOOLEAN NOT NULL,
    order_type TEXT NOT NULL,
    stock_price DECIMAL NOT NULL,
    quantity INT NOT NULL,
    user_id UUID NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_stock_transaction_id) REFERENCES stock_transactions(id)
);

CREATE TABLE wallet_transactions (
    id uuid primary key default uuid_generate_v4(),
    stock_transaction_id uuid,
    wallet_id uuid,
    user_stock_transaction_id uuid,
    date_created timestamp default current_timestamp,
    date_modified timestamp default current_timestamp,
    is_debit boolean not null,
    amount decimal not null,
    user_id uuid not null,
    timestamp timestamp default current_timestamp,
    foreign key (stock_transaction_id) references stock_transactions(id),
    foreign key (wallet_id) references wallets(id)
);
--Following operation initially generated by CHATGPT o1
--https://chatgpt.com/share/67e4a820-ff4c-8006-b982-d179f9ce734f
--Adjusted heavily.
---------------------------------------------------------------------------------
    -- SUB FUNCTION TO PROCESS STOCK TRADE FOR BUYER OR SELLER
---------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION process_trade(
    v_stock_tx_id     UUID,
    v_user_id            UUID,
    v_stock_id                UUID,
    v_unit_stock_price        DECIMAL,
    v_trade_quantity          INT,
    v_total_amount            DECIMAL(18,2),
    v_is_buy                  BOOLEAN DEFAULT TRUE
)
RETURNS VOID
Language plpgsql
AS $$
DECLARE
    v_wallet_id          UUID;
    v_wallet_tx_id       UUID;
    v_new_stock_tx_id        UUID;
    v_new_balance        DECIMAL(18,2);
    v_required_quantity  INT;          -- For partial-fill logic
    v_existing_quantity  INT;          -- For partial-fill logic
    v_order_type         TEXT;          -- For order type
    v_order_status       TEXT;          -- For order status
BEGIN
        -- 1) Calculate total money to be exchanged
        -- total_amount := v_unit_stock_price * v_trade_quantity; -- Already passed as parameter

        -- Determine order type based on is_buy flag
    if v_is_buy = true then
        v_order_type := 'MARKET';
    else
        v_order_type := 'LIMIT';
    end if;
---------------------------------------------------------------------------------
    -- STEP 1: UPDATE WALLET (subtract funds)
    ---------------------------------------------------------------------------------
    IF v_is_buy THEN
        UPDATE wallets
           SET balance = balance - v_total_amount,
               date_modified = CURRENT_TIMESTAMP
            WHERE user_id = v_user_id
            RETURNING id, balance
            INTO v_wallet_id, v_new_balance;
    ELSE
        UPDATE wallets
           SET balance = balance + v_total_amount,
               date_modified = CURRENT_TIMESTAMP
            WHERE user_id = v_user_id
            RETURNING id, balance
            INTO v_wallet_id, v_new_balance;
    END IF;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No wallet found for user_id = %', v_user_id;
    END IF;

    ---------------------------------------------------------------------------------
    -- STEP 2: Check if balance is below 0
    ---------------------------------------------------------------------------------
    IF v_new_balance < 0 THEN
        RAISE EXCEPTION 'balance (user_id=%) would go negative. Rolling back.', 
                        v_user_id;
    END IF;

    ---------------------------------------------------------------------------------
    -- STEP 3: CREATE WALLET TRANSACTION (is_debit = true)
    ---------------------------------------------------------------------------------
    INSERT INTO wallet_transactions (
        stock_transaction_id,
        wallet_id,
        date_created,
        date_modified,
        is_debit,
        amount,
        user_id
    )
    VALUES (
        v_stock_tx_id,
        v_wallet_id,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        v_is_buy,
        v_total_amount,
        v_user_id
    )
    RETURNING id
    INTO v_wallet_tx_id;

    
    ---------------------------------------------------------------------------------
    -- STEP 4: UPDATE STOCK TRANSACTION (Partial Fill or Complete)
    ---------------------------------------------------------------------------------
    SELECT quantity, order_status 
        INTO v_required_quantity, v_order_status
        FROM stock_transactions 
        WHERE id = v_stock_tx_id;
     
    IF NOT FOUND THEN
        RAISE EXCEPTION 'No stock_transaction found for tx_id = %', v_stock_tx_id;
    END IF;
    IF v_order_status = 'PARTIALLY_COMPLETE' THEN
        SELECT COALESCE(SUM(quantity), 0)
            INTO v_existing_quantity
            FROM stock_transactions 
        WHERE parent_stock_transaction_id = v_stock_tx_id AND order_status = 'COMPLETED';
    ELSE
        v_existing_quantity := 0;
    END IF;

    --  partial fill logic:
    IF v_required_quantity - v_existing_quantity > v_trade_quantity THEN
    
        IF v_order_status = 'IN_PROGRESS' THEN
            UPDATE stock_transactions
            SET order_status = 'PARTIALLY_COMPLETE',
                date_modified = CURRENT_TIMESTAMP
            WHERE id = v_stock_tx_id;
        END IF;

        -- Create child tx for leftover quantity
        INSERT INTO stock_transactions (
            parent_stock_transaction_id,
            stock_id,
            user_id,
            wallet_transaction_id,
            quantity,
            stock_price,
            is_buy,
            order_status,
            order_type,
            date_created,
            date_modified
        )
        VALUES (
            v_stock_tx_id,
            v_stock_id,
            v_user_id,
            v_wallet_tx_id,
            v_trade_quantity,
            v_unit_stock_price,
            v_is_buy,
            'COMPLETED',
            v_order_type,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        )
        RETURNING id
        INTO v_new_stock_tx_id;
       --update wallet transaction to have the correct stock transaction id.
        UPDATE wallet_transactions
        SET stock_transaction_id = v_new_stock_tx_id
        WHERE id = v_wallet_tx_id;
    ELSE
        -- If exactly matched or overfilled, mark the original as filled
        UPDATE stock_transactions
           SET order_status = 'COMPLETED',
               date_modified = CURRENT_TIMESTAMP,
               wallet_transaction_id = v_wallet_tx_id,
               stock_price = v_unit_stock_price
         WHERE id = v_stock_tx_id;
    END IF;
END;
$$;

---------------------------------------------------------------------------------
    -- MASTER FUNCTION TO PROCESS STOCK TRADE FOR BUYER AND SELLER
---------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION process_stock_trade(
    v_buyer_tx_id        UUID,
    v_seller_tx_id       UUID,
    v_buyer_user_id      UUID,
    v_seller_user_id     UUID,
    v_stock_id           UUID,
    v_unit_stock_price   DECIMAL,
    v_trade_quantity     INT,
    v_stock_name         TEXT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_total_amount      DECIMAL(18,2);
BEGIN
    -- 1) Calculate total money to be exchanged
    v_total_amount := v_unit_stock_price * v_trade_quantity;

    ---------------------------------------------------------------------------------
    -- STEP 1: UPDATE BUYER DETAILS (wallet, stock transaction, etc.)
    ---------------------------------------------------------------------------------
    PERFORM process_trade(
        v_buyer_tx_id,
        v_buyer_user_id,
        v_stock_id,
        v_unit_stock_price,
        v_trade_quantity,
        v_total_amount,
        true
    );

    ---------------------------------------------------------------------------------
    -- STEP 2: UPDATE SELLER DETAILS (wallet, stock transaction, etc.)
    ---------------------------------------------------------------------------------
    PERFORM process_trade(
        v_seller_tx_id,
        v_seller_user_id,
        v_stock_id,
        v_unit_stock_price,
        v_trade_quantity,
        v_total_amount,
        false
    );
    
    ---------------------------------------------------------------------------------
    -- STEP 3: UPDATE USER STOCKS FOR BUYER
    ---------------------------------------------------------------------------------
    INSERT INTO user_stocks (
        user_id,
        stock_id,
        stock_name,
        quantity,
        date_created,
        date_modified
    )
    VALUES (
        v_buyer_user_id,
        v_stock_id,
        v_stock_name,
        v_trade_quantity,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
    ON CONFLICT (user_id, stock_id)
    DO UPDATE SET 
        quantity      = user_stocks.quantity + EXCLUDED.quantity,
        date_modified = CURRENT_TIMESTAMP;
    -- If we reach here with no exception, all steps are successful.
END;
$$;
